### ISSUE TITLE
Match 100% of `grTPeach` and 69.69% of `grTMewtwo`

### ISSUE THREAD

**Issue by LakeinLove** [doldecomp/melee#1011]
- [x] #1013
  - [x] https://decomp.me/scratch/aaw2L
  - [x] https://decomp.me/scratch/VBgbX
  - [x] https://decomp.me/scratch/qplEf
  - [x] https://decomp.me/scratch/iiE2X
  - [x] https://decomp.me/scratch/1kgI1
  - [x] https://decomp.me/scratch/kGOOu
  - [x] https://decomp.me/scratch/NfBMZ
  - [x] https://decomp.me/scratch/Oh4S7
  - [x] https://decomp.me/scratch/nxe3p
  - [x] https://decomp.me/scratch/f9rqG
  - [x] https://decomp.me/scratch/vUpCo
  - [x] https://decomp.me/scratch/uhINa
- [x] #1014
  - [x] https://decomp.me/scratch/ngexB
  - [x] https://decomp.me/scratch/pwnH5
  - [x] https://decomp.me/scratch/kLgW7
  - [x] https://decomp.me/scratch/Pkj91 (This has not been completed and is awating on the peach completion)
  - [x] https://decomp.me/scratch/vRngr
  - [x] https://decomp.me/scratch/HbHIu
  - [x] https://decomp.me/scratch/68eWF
  - [x] https://decomp.me/scratch/a6CUZ
  - [x] https://decomp.me/scratch/OzbvZ

**Comment by LakeinLove** [comment]
`grTMewtwo` functions are named wrong as grTMars not grTMt. Room for a bulk-fix at .c file collation time.

(Context: this function:

```asm
.global grTMars_8022227C
grTMars_8022227C:
/* 8022227C 0021EE5C  38 60 00 00 */	li r3, 0
/* 80222280 0021EE60  4E 80 00 20 */	blr
```

is repeated throughout the file with different names. if you see it use it's name and insert the code from : https://decomp.me/scratch/kLgW7 (The third link in the list))

**Comment by ribbanya** [comment]
@LakeinLove Nice work, thank you!
