### ISSUE TITLE
it2ADA.s

### ISSUE THREAD

**Issue by Walnut356** [doldecomp/melee#1057]
- [x] [`it_802ADA1C`](https://decomp.me/scratch/PKnOd)
- [x] [`it_802ADAF0`](https://decomp.me/scratch/RTrFO)
- [x] [`it_802ADB48`](https://decomp.me/scratch/hHCyI)
- [x] [`it_802ADB80`](https://decomp.me/scratch/Ujjfy)
- [x] [`it_802ADBB0`](https://decomp.me/scratch/NCUzu)
- [x] [`it_802ADBE4`](https://decomp.me/scratch/lx3XC)

**Comment by Walnut356** [comment]
I'll attempt a PR myself next time - seeing how y'all integrate this file should be enough for me to figure it out ^^

**Comment by ribbanya** [comment]
Thanks! Will PR this later today or tomorrow.
