### ISSUE TITLE
Match some ftCo_YoshiEgg.s functions

### ISSUE THREAD

**Issue by JohnnyUrosevic** [doldecomp/melee#1378]
Was planning on merging these myself but been busy so maybe someone can get to it before me.

- [ftCo_800BBC88](https://decomp.me/scratch/yOnLQ)
- [ftCo_YoshiEgg_Phys](https://decomp.me/scratch/2ql2I)
- [ftCo_YoshiEgg_Coll](https://decomp.me/scratch/SviWv)
- [ftCo_800BC388](https://decomp.me/scratch/uMPUf)
- [ftCo_800BC3AC](https://decomp.me/scratch/4coUF)
- [ftCo_800BC3D0](https://decomp.me/scratch/1PMgZ)

**Comment by ribbanya** [comment]
Hi, thanks! That file is down to a single regswap in `ftCo_800BBED4`, so if you have time maybe you can look at it.

## Report of `melee/ft/chara/ftCommon/ftCo_YoshiEgg.c`
Function|Size|Score|Max|%
-|-|-|-|-
**File**|`1.97 KB`|`45`|`49,200`|`99.91%`
`ftCo_800BBED4`|`732 bytes`|`45`|`18,300`|`99.75%`
`ftCo_800BBCC0`|`532 bytes`|`0`|`13,300`|`100.00%`
`ftCo_YoshiEgg_Anim`|`340 bytes`|`0`|`8,500`|`100.00%`
`ftCo_800BC3D0`|`104 bytes`|`0`|`2,600`|`100.00%`
`ftCo_YoshiEgg_Coll`|`72 bytes`|`0`|`1,800`|`100.00%`
`ftCo_800BBC88`|`56 bytes`|`0`|`1,400`|`100.00%`
`ftCo_YoshiEgg_Phys`|`56 bytes`|`0`|`1,400`|`100.00%`
`ftCo_800BC388`|`36 bytes`|`0`|`900`|`100.00%`
`ftCo_800BC3AC`|`36 bytes`|`0`|`900`|`100.00%`
`ftCo_YoshiEgg_IASA`|`4 bytes`|`0`|`100`|`100.00%`
