### ISSUE TITLE
Rename KAR-addressed functions

### ISSUE THREAD

**Issue by ribbanya** [doldecomp/melee#476]
@PsiLupan 
> Left these comments on functions I don't know the names of, which exist in KAR but are stripped in melee because their only uses are auto-inlined. Maybe Psi knows what to call them.

_Originally posted by @r-burns in https://github.com/doldecomp/melee/pull/475#discussion_r952153046_

**Comment by PsiLupan** [comment]
`func_80382400` is `int hsdChangeClass(void* object, void* class_info);` - The types are wrong.

`func_80420FBC` is  `void class_set_flags(HSD_ClassInfo* info, class_state set, class_state reset);`

where that enum is:
```
enum class_state {
		HSD_CLASS_NONE = 0,
		HSD_CLASS_READY = 1
};
```

`func_804211B4` is `void	ForgetClassLibraryChild(const char* library_name, HSD_ClassInfo* info);`

`func_804212F4` is `void	DumpClassStat(HSD_ClassInfo* info, int level);`

`func_80382854` is `void hsdDumpClassStat(HSD_ClassInfo* info, int recursive, int level);`

**Comment by ribbanya** [comment]
> `func_80420FBC` is `void class_set_flags(HSD_ClassInfo* info, class_state set, class_state reset);`
> 
> where that enum is:
> 
> ```
> enum class_state {
> 		HSD_CLASS_NONE = 0,
> 		HSD_CLASS_READY = 1
> };
> ```

This should be implemented as a `BOOL` on our end imo.

**Comment by ribbanya** [comment]
I think we've pretty much covered all these by now.
