### ISSUE TITLE
Address remaining issues with `MSL/math`

### ISSUE THREAD

**Issue by ribbanya** [doldecomp/melee#478]
> Every function of math has been fully matched and decompiled except for func_803265A8. (which I'll do very soon, unless one of you wants to pick it up for themselves)
> 
> The currently linked math.o file is from the asm so this has to be changed as well as soon as func_803265A8 is matched.
> 
> * [ ]  Match func_803265A8
> * [ ]  Rename variables to what they do
> * [ ]  Reformat function bodies/Remove comments
> * [x]  Rename functions to what they do
> * [ ]  Link math.o from "src"

_Originally posted by @FluentCoding in https://github.com/doldecomp/melee/pull/235#issue-1093845578_

**Comment by Ka-lua** [comment]
Partial match of the remaining natural logarithm function: https://decomp.me/scratch/UmjGN
The function in the scratch is logically equivalent. Biggest problem is matching the asm instructions for computing the inner return value expression.

**Comment by ribbanya** [comment]
Nice work. If nothing else it can be used for other platforms. Have you tried using `asm { }` blocks to force a match?

**Comment by Ka-lua** [comment]
I didn't try integrating it yet, it's only a scratch so far. But I understand the logic better now (the original scratch is quite old) and reworked the scratch to reflect that. But it would probably be fine to just put it in ASM blocks unless someone can fix these annoying issues.

**Comment by ribbanya** [comment]
I'm going to mark this as resolved via #1166. The remaining issues in the OP are fairly routine tasks of matching `math.c` and should be resolved naturally as part of that effort.
