### ISSUE TITLE
Replace `USE_QUATERNION` with `JOBJ_USE_QUATERNION`

### ISSUE THREAD

**Issue by ribbanya** [doldecomp/melee#536]

**Comment by r-burns** [comment]
It seems that this applies to the other jobj bitflag defines based on assert statements.

https://github.com/doldecomp/melee/blob/1040fe1a9231911a7cdc4aaf0b4c7e1b247c9f6c/src/sysdolphin/baselib/jobj.c#L1354

I think our JOBJ_ function-like macros are fake, and these are actually JOBJ_ prefixed bitflags which are manually and-ed with jobj->flags.
