### ISSUE TITLE
Match `func_80031640`

### ISSUE THREAD

**Issue by GreatWyrm** [doldecomp/melee#596]
https://decomp.me/scratch/5YZak

In cm/cmsnap.s

```c
void func_80031640(HSD_GObj* arg0, s32 arg1) {
    switch (lbl_80453060[0]) {
        case 1:
            func_800122C8(&lbl_80453060[1], 0, 0, 0);
            lbl_80453060[0] = 2;
            return;
        case 2:
        case 3:
        case 4:
            lbl_80453060[0] += 1;
        case 0:
        default:
            return;
    }
}
```

**Comment by ribbanya** [comment]
Thanks!

**Comment by r-burns** [comment]
UnclePunch GTME01.map calls this function Snapshot_CaptureScreen

**Comment by PsiLupan** [comment]
That name is kinda terrible, since it isn't really doing that directly. That function it calls may be better suited for that.

Should probably look at the caller, since it seems like it's buffering what it does (and without something resetting the switch condition, it would only run once ever).

**Comment by ribbanya** [comment]
Superseded by #425.
