### ISSUE TITLE
Match gr/grtluigi.c

### ISSUE THREAD

**Issue by jeffmao99** [doldecomp/melee#598]
- [x] [`func_80221C10`](https://decomp.me/scratch/L9klz)
- [x] [`lbl_80221C14`](https://decomp.me/scratch/vGpE6)
- [x] [`lbl_80221C84`](https://decomp.me/scratch/F2sax)
- [x] [`lbl_80221C88`](https://decomp.me/scratch/74RUK)
- [x] [`lbl_80221CAC`](https://decomp.me/scratch/4yhKI)
- [x] [`func_80221CB4`](https://decomp.me/scratch/wXG0o)
- [x] [`lbl_80221D9C`](https://decomp.me/scratch/ai4GG)
- [x] [`lbl_80221DC8`](https://decomp.me/scratch/Glhco)
- [x] [`lbl_80221DD0`](https://decomp.me/scratch/Tv62A)
- [x] [`lbl_80221DD4`](https://decomp.me/scratch/8p8gC)
- [x] [`lbl_80221DD8`](https://decomp.me/scratch/zJQC5)
- [x] [`lbl_80221E28`](https://decomp.me/scratch/NKF9a)
- [x] [`lbl_80221E30`](https://decomp.me/scratch/3UciJ)
- [x] [`lbl_80221E64`](https://decomp.me/scratch/GgNzz)
- [x] [`lbl_80221E68`](https://decomp.me/scratch/6d9Di)
- [x] [`lbl_80221EB8`](https://decomp.me/scratch/rEeRe)
- [x] [`lbl_80221EC0`](https://decomp.me/scratch/AeHLp)
- [x] [`lbl_80221EE0`](https://decomp.me/scratch/f3uZM)
- [x] [`lbl_80221EE4`](https://decomp.me/scratch/yeq3w)
- [x] [`lbl_80221EEC`](https://decomp.me/scratch/11yWE)

**Comment by ribbanya** [comment]
Nice work, thanks!
