### ISSUE TITLE
Match `func_8007C114` and `func_800C555C`

### ISSUE THREAD

**Issue by RageCage64** [doldecomp/melee#767]
- [x] #768
    `func_8007C114`: https://decomp.me/scratch/QP6Eg
    Checks if the fighter has an item, if it does and it's the hammer it checks if the head should fall off (by calling `func_800C555C`). Then it sets a bit flag. 

- [x] #1026
  - [x] `func_800C555C`: https://decomp.me/scratch/XPrfZ
        Checks if the hammer the `HSD_GObj` is holding should have its head fall off by calling `func_8026C16C`.

**Comment by ribbanya** [comment]
Thanks!
